### ISSUE TITLE
Vcash wallets not showing up

### ISSUE THREAD

**Issue by matu0** [xCoreDev/vcash#37] opened 2018-01-04 08:01 UTC
I downloaded vcash-client-0.6.0.4-win64 and downloaded all the blocks. I created wallets, but they are not showing up on explorer. i.e. 
https://explorer.vchain.info//address/VooqwP8WwE8dRv8Q6oj3G1sftDoTR6uAJ4
Should I edit the config file somehow?

Thanks!

**Comment by bobfeldbauer** [comment] 2018-01-04 09:16
Just creating an address locally in your wallet doesn't interact with the blockchain / network. You need to send coins to that address for it to show up on the block explorer.

**Comment by sum01** [comment] 2018-01-05 22:44
Going to close this since it's not a bug.

**Closed as completed by sum01** 2018-01-05 22:44 UTC
Labels: invalid
